# Generated by Django 4.2.20 on 2025-04-06 10:21

import customer_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=customer_auth.models.user_directory_path),
        ),
    ]
