# Generated by Django 5.2.1 on 2025-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0002_customeruser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='email_en',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='email_ru',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='email_uz',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='password_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='password_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='password_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone_en',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone_ru',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone_uz',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone'),
        ),
    ]
