# Generated by Django 4.2.20 on 2025-05-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0003_customeruser_email_en_customeruser_email_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='password_en',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='password_ru',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='password_uz',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OAuth ID'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='oauth_provider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OAuth Provider'),
        ),
    ]
