# Generated by Django 4.2.20 on 2025-06-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0004_remove_customeruser_password_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone_en',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone_ru',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone_uz',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone'),
        ),
    ]
