# Generated by Django 4.2.20 on 2025-06-19 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0006_customerotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 12, 13, 56, 681732, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
