# Generated by Django 4.2.20 on 2025-06-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0007_customerotp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
