# Generated by Django 5.2.1 on 2025-07-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0008_customeruser_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Is Email Verified'),
        ),
    ]
