# Generated by Django 5.2.1 on 2025-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0009_customeruser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
