# Generated by Django 5.2.1 on 2025-08-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0010_customeruser_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerotp',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
