# Generated by Django 4.2.20 on 2025-05-25 06:33

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(max_length=300)),
                ('duration', models.CharField(choices=[('1 day', '1 Day'), ('2 day', '2 Days'), ('3 day', '3 Days'), ('4 day', '4 Days'), ('5 day', '5 Days'), ('6 day', '6 Days'), ('7 day', '7 Days')], max_length=10)),
                ('about', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('KRW', 'KRW (₩)')], default='USD', max_length=10)),
                ('trip_start_date', models.DateField(blank=True, null=True)),
                ('trip_end_date', models.DateField(blank=True, null=True)),
                ('group_size', models.PositiveIntegerField()),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek'), ('ko', 'Korean')], max_length=20)),
                ('age_min', models.PositiveIntegerField(default=18)),
                ('age_max', models.PositiveIntegerField(default=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.country')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='partners.partnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TourTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.tourtag'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tourtype'),
        ),
        migrations.CreateModel(
            name='IncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_items', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('day_title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('accommodation', models.CharField(blank=True, max_length=255)),
                ('included_meals', models.CharField(blank=True, max_length=255)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='tours.tour')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('tour', 'day_number')},
            },
        ),
    ]
