# Generated by Django 4.2.20 on 2025-05-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/main_images/'),
        ),
    ]
