# Generated by Django 4.2.20 on 2025-05-25 07:36

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('tours', '0002_tour_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city'),
        ),
    ]
