# Generated by Django 4.2.20 on 2025-06-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='use_detailed_pricing',
            field=models.BooleanField(default=False, help_text='Enable age-specific pricing (e.g., adult, child)'),
        ),
        migrations.CreateModel(
            name='TourPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_pricing', to='tours.tour')),
            ],
            options={
                'unique_together': {('tour', 'age_category')},
            },
        ),
    ]
