# Generated by Django 4.2.20 on 2025-06-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0004_remove_customeruser_password_en_and_more'),
        ('tours', '0004_tour_use_detailed_pricing_tourpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='customer_auth.customeruser')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='tours.tour')),
            ],
            options={
                'unique_together': {('customer', 'tour')},
            },
        ),
    ]
