# Generated by Django 4.2.20 on 2025-06-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
