# Generated by Django 4.2.20 on 2025-06-05 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20250605_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
