# Generated by Django 5.2.1 on 2025-07-02 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('tours', '0009_itinerary_latitude_itinerary_location_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='booking_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of bookings for this tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='last_booked_at',
            field=models.DateTimeField(blank=True, help_text='When this tour was last booked', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating out of 5', max_digits=3),
        ),
        migrations.AddField(
            model_name='tour',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of ratings received'),
        ),
        migrations.AddField(
            model_name='tour',
            name='trending_score',
            field=models.FloatField(default=0.0, help_text='Calculated score for trending algorithm'),
        ),
        migrations.AddField(
            model_name='tour',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this tour has been viewed'),
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country')),
            ],
            options={
                'unique_together': {('name', 'city', 'country')},
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.destination'),
        ),
        migrations.CreateModel(
            name='TourAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('booking', 'Booking'), ('search', 'Search'), ('wishlist_add', 'Wishlist Add'), ('engagement', 'Engagement')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='tours.tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
