# Generated by Django 5.2.1 on 2025-07-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0008_customeruser_updated_at'),
        ('tours', '0010_tour_booking_count_tour_last_booked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touranalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_auth.customeruser'),
        ),
    ]
