# Generated by Django 5.2.1 on 2025-08-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_tourrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Mark tour as active or inactive'),
        ),
    ]
