# Generated by Django 5.2.1 on 2025-08-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_auto_20250816_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.PositiveIntegerField(help_text='Enter number of days for the tour'),
        ),
    ]
