# Generated by Django 5.2.1 on 2025-08-26 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_alter_tour_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('day_title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='tours.tour')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('tour', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ItinerarySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='tours.itineraryday')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
    ]
