# Generated by Django 5.2.1 on 2025-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_itineraryday_itineraryslot_delete_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Additional hours for short tours or half-day tours', null=True),
        ),
    ]
