# Generated by Django 5.2.1 on 2025-08-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_tour_duration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Enter number of days for the tour', null=True),
        ),
    ]
