# Generated by Django 5.2.1 on 2025-09-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_remove_tour_duration_tour_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='accommodation',
            field=models.CharField(blank=True, help_text='E.g. Hotel name or place of stay', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='included_meals',
            field=models.TextField(blank=True, help_text='E.g. Breakfast, Lunch, Dinner', null=True),
        ),
        migrations.AddField(
            model_name='itineraryslot',
            name='included_meals',
            field=models.TextField(blank=True, help_text='E.g. Breakfast, Lunch, Dinner', null=True),
        ),
    ]
