# Generated by Django 5.2.1 on 2025-09-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_itineraryday_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryday',
            name='included_meals',
            field=models.CharField(blank=True, help_text='E.g. Breakfast, Lunch, Dinner', null=True),
        ),
    ]
