# Generated by Django 4.2.20 on 2025-06-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_auth', '0004_remove_customeruser_password_en_and_more'),
        ('tours', '0009_itinerary_latitude_itinerary_location_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='customer_auth.customeruser')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_entries', to='tours.tour')),
            ],
            options={
                'unique_together': {('customer', 'tour')},
            },
        ),
    ]
