# Generated by Django 5.2.1 on 2025-07-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_tourbooking_bookingparticipant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingparticipant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
    ]
