# Generated by Django 5.2.1 on 2025-07-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0008_customeruser_updated_at'),
        ('order', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PAYMENT_DENIED', 'Payment Denied'), ('PAYMENT_FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='CardholderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=100)),
                ('administrative_area', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardholder_info', to='order.payment')),
            ],
        ),
        migrations.CreateModel(
            name='FailedCardSaveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_data', models.JSONField()),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.tourbooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_auth.customeruser')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_profile_id', models.CharField(max_length=255)),
                ('payment_token_id', models.CharField(max_length=255, unique=True)),
                ('card_type', models.CharField(max_length=20)),
                ('last4', models.CharField(max_length=4)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=4)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to='customer_auth.customeruser')),
            ],
        ),
    ]
