# Generated by Django 5.2.1 on 2025-08-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_tourbooking_status_cardholderinfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourbooking',
            options={'verbose_name': 'All List', 'verbose_name_plural': ' All List'},
        ),
    ]
